/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth-business)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth-business)'}/set-up` | `/set-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(business)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(business)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search-container` | `/search-container`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth-business)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth-business)'}/set-up` | `/set-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(business)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(business)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/search-container` | `/search-container`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth-business)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth-business)'}/set-up${`?${string}` | `#${string}` | ''}` | `/set-up${`?${string}` | `#${string}` | ''}` | `${'/(business)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(business)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/search-container${`?${string}` | `#${string}` | ''}` | `/search-container${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth-business)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth-business)'}/set-up` | `/set-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(business)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(business)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search-container` | `/search-container`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
